---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(raster)
library(stars)
library(sf)
library(there)
library(mapview)
```

```{r}
landcov_stars <- read_stars(here_file("Projects", "Penn_migration_model", "phys_sclass_pa_reclassed.tif")) 

used_mig_pa <- st_read(here_file("Data", "Movebank_locations"), "migratory_points_pa_8_3_2020") %>%
  st_transform(st_crs(landcov_stars)) %>%
  transmute(ID = ID, time = time, type = "Used")

landcov_raster <- raster(here_file("Projects", "Penn_migration_model", "phys_sclass_pa_reclassed.tif")) 
```

Generating random points
```{r}
map(1:nrow(used_mig_pa), function(x){
  used_mig_pa[x,] %>%
    pull(geometry) %>%
    st_buffer(5000) %>%
    st_sample(1) ->
    new_geom
  
  used_mig_pa[x,] %>%
    pull(ID) ->
    new_ID
  
  used_mig_pa[x,] %>%
    pull(time) ->
    new_time
  
  tibble(ID = new_ID, time = new_time, type = "Available", geometry = new_geom)
}) -> available_mig_pa
  
available_mig_pa <- exec(bind_rows, available_mig_pa)
```


```{r}
points_mig_pa <- bind_rows(used_mig_pa, available_mig_pa)
```


```{r}
points_mig_pa %>%
  st_buffer(100) ->
  buffer_mig_pa
```


```{r include=FALSE}
map(1:nrow(buffer_mig_pa), function(i){
  buffer_mig_pa[i,] %>%
    as_Spatial() %>% 
    raster::extract(x = landcov_raster, y = .)
}) -> proportion_results
```


```{r}
pct_count <- function(x, r){
  a <- unlist(x)
  b <- a == r
  sum(b)*100/length(b)
}

proportion_results %>%
  map(function(x){
    tibble(`Open Water` = pct_count(x = x, r = 1), 
           Developed = pct_count(x = x, r = 2),
           Agricultural = pct_count(x = x, r = 3),
           `Developed-Roads` = pct_count(x = x, r = 4),
           `Developed-Low Intensity` = pct_count(x = x, r = 5),
           `Exotic Herbaceous` = pct_count(x = x, r = 6),
           `Exotic Tree-Shrub` = pct_count(x = x, r = 7),
           `Conifer-Hardwood` = pct_count(x = x, r = 8),
           `Hardwood` = pct_count(x = x, r = 9),
           `Developed-Medium Intensity` = pct_count(x = x, r = 10),
           `Hardwood C` = pct_count(x = x, r = 11),
           `Conifer-Hardwood C` = pct_count(x = x, r = 12),
           `Hardwood B` = pct_count(x = x, r = 13),
           `Conifer-Hardwood B`= pct_count(x = x, r = 14),
           `Riparian` = pct_count(x = x, r = 15),
           `Hardwood E` = pct_count(x = x, r = 16),
           `Conifer-Hardwood E` = pct_count(x = x, r = 17),
           `Conifer C` = pct_count(x = x, r = 18),
           `Conifer E` = pct_count(x = x, r = 19),
           `Riparian C` = pct_count(x = x, r = 20),
           `Hardwood A` = pct_count(x = x, r = 21),
           `Riparian A` = pct_count(x = x, r = 22),
           `Developed-High Intensity` = pct_count(x = x, r = 23),
           `Riparian E` = pct_count(x = x, r = 24),
           `Riparian B` = pct_count(x = x, r = 25),
           `Conifer A` = pct_count(x = x, r = 26),
           `Conifer` = pct_count(x = x, r = 27),
           `Conifer-Hardwood A` = pct_count(x = x, r = 28),
           `Hardwood D` = pct_count(x = x, r = 29),
           `Conifer-Hardwood D` = pct_count(x = x, r = 30),
           `Conifer D` = pct_count(x = x, r = 31),
           `Riparian D` = pct_count(x = x, r = 32),
           `Conifer B` = pct_count(x = x, r = 33),
           `Quarries` = pct_count(x = x, r = 34),
           `Sparsely Vegetated` = pct_count(x = x, r = 35),
           `Grassland` = pct_count(x = x, r = 36),
           `Shrubland` = pct_count(x = x, r = 37),
           `Ruderal Wet Meadow and Marsh` = pct_count(x = x, r = 38))
  }) %>%
  exec(bind_rows, .) ->
  proportion_results_df
```


```{r}
points_mig_pa_results <- bind_cols(points_mig_pa, proportion_results_df)
```


```{r}
points_mig_pa_results %>%
  pivot_longer(cols = `Open Water`:`Ruderal Wet Meadow and Marsh`, names_to = "landcov") ->
  points_mig_pa_pivotresults
```

```{r}
ggplot(data = points_mig_pa_pivotresults, mapping = aes(x = landcov, y = value, fill = type)) +
  geom_boxplot() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  #geom_bar(stat = "identity", position = "dodge")
```

