---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(raster)
setwd("D:/OneDrive - University of Maine System/MaineAnalysis")
library(there)
```


```{r}
nlcd <- raster(here_file("Data", "NLCD_products", "landcover_2016", "NLCD_2016_PA.tif"))

reclass_dev_matrix <- c(0 , 19, 0,
                    20, 25, 1,
                    26, 99, 0) %>%
  matrix(ncol = 3, byrow = TRUE)

reclass_agri_matrix <- c(0 , 79, 0,
                    80, 88, 1,
                    89, 99, 0) %>%
  matrix(ncol = 3, byrow = TRUE)

nlcd_dev <- reclassify(nlcd, rcl = reclass_dev_matrix) %>% as.integer()
nlcd_agri <- reclassify(nlcd, rcl = reclass_agri_matrix) %>% as.integer()

values(nlcd_dev)[values(nlcd_dev) == 128] <- NA
values(nlcd_agri)[values(nlcd_agri) == 128] <- NA

writeRaster(nlcd_dev, here_file("Projects", "Penn_migration_model", "nlcd_2016_devpatches.tif"), overwrite = TRUE, datatype = "INT1U")

writeRaster(nlcd_agri, here_file("Projects", "Penn_migration_model", "nlcd_2016_agripatches.tif"), overwrite = TRUE, datatype = "INT1U")

```

