---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggmap)
library(rgdal)
library(raster)
library(sf)
library(parallel)
library(pbapply)
library(leaflet)
library(colorspace)
library(RColorBrewer)
library(leaflet.providers)
library(leaflet.esri)
library(there)
```


```{r}
m10r0 <- raster(here_file("Projects", "penn_shiny_app", "prerender_PA_app", "m10r0.tif"))
m0r10 <- raster(here_file("Projects", "penn_shiny_app", "prerender_PA_app", "m0r10.tif"))
```

rendering a map for the migratory layer
```{r}
iterated_layer <- m10r0
iterated_name <- "m10r0"

quantiles <- raster::quantile(iterated_layer, 1:100/100)

intervals <- findInterval(getValues(iterated_layer), quantiles)
iterated_layer <- setValues(iterated_layer, intervals)
#iterated_layer <- iterated_layer*5 # scaling from 0 to 100

#pal <- oompaBase::jetColors(100)
pal_fun <- colorNumeric(palette = "RdYlBu", domain = c(min(values(iterated_layer), na.rm = TRUE), max(values(iterated_layer), na.rm = TRUE)), na.color = NA, reverse = TRUE)


#pal_fun <- colorQuantile(palette = pal, domain = c(min(values(iterated_layer), na.rm = TRUE), max(values(iterated_layer), na.rm = TRUE)), na.color = NA, n = 10)

if(iterated_name == "m10r0"){
  polygon_weight <- 1
} else if (iterated_name == "m9r1"){
  polygon_weight <- 0.85
} else if (iterated_name == "m8r2"){
  polygon_weight <- 0.7
} else if(iterated_name == "m7r2"){
  polygon_weight <- 0.6
} else {
  polygon_weight <- 0.5
}

leaflet(options = leafletOptions(zoomControl = FALSE,attributionControl=FALSE)) %>%
  addEsriBasemapLayer(esriBasemapLayers$Topographic, autoLabels = TRUE, group = "Topographic map") %>%
    #addEsriBasemapLayer(esriBasemapLayers$Gray, autoLabels = FALSE, group = "Topographic map") %>%
  #addLegend(pal = pal_fun, values = values(iterated_layer), title = "Percentile") %>%
  addRasterImage(x = iterated_layer, opacity = 0.8, colors = pal_fun, group = "Predictive layer", project = FALSE) %>%
  addScaleBar(position = "bottomleft") %>%
  setView(lat = 40.870401, lng = -77.659887, zoom = 7) ->
  iterated_leaflet

iterated_leaflet %>%
  mapview::mapshot(file = "m10r0_nolegend.jpg", vwidth = 575, vheight = 375, remove_controls = NULL)

```

And the residential layer
```{r}
iterated_layer <- m0r10
iterated_name <- "m0r10"

quantiles <- raster::quantile(iterated_layer, 1:100/100)

intervals <- findInterval(getValues(iterated_layer), quantiles)
iterated_layer <- setValues(iterated_layer, intervals)
#iterated_layer <- iterated_layer*5 # scaling from 0 to 100

#pal <- oompaBase::jetColors(100)
pal_fun <- colorNumeric(palette = "RdYlBu", domain = c(min(values(iterated_layer), na.rm = TRUE), max(values(iterated_layer), na.rm = TRUE)), na.color = NA, reverse = TRUE)


#pal_fun <- colorQuantile(palette = pal, domain = c(min(values(iterated_layer), na.rm = TRUE), max(values(iterated_layer), na.rm = TRUE)), na.color = NA, n = 10)

if(iterated_name == "m10r0"){
  polygon_weight <- 1
} else if (iterated_name == "m9r1"){
  polygon_weight <- 0.85
} else if (iterated_name == "m8r2"){
  polygon_weight <- 0.7
} else if(iterated_name == "m7r2"){
  polygon_weight <- 0.6
} else {
  polygon_weight <- 0.5
}

leaflet(options = leafletOptions(zoomControl = FALSE, attributionControl=FALSE)) %>%
  addEsriBasemapLayer(esriBasemapLayers$Topographic, autoLabels = TRUE, group = "Topographic map") %>%
  #addEsriBasemapLayer(esriBasemapLayers$Gray, autoLabels = FALSE, group = "Topographic map") %>%
  #addLegend(pal = pal_fun, values = values(iterated_layer), title = "Percentile") %>%
  addRasterImage(x = iterated_layer, opacity = 0.8, colors = pal_fun, group = "Predictive layer", project = FALSE) %>%
  addScaleBar(position = "bottomleft") %>%
  setView(lat = 40.870401, lng = -77.659887, zoom = 7) -> #lat = 40.870401, lng = -77.329887
  iterated_leaflet

iterated_leaflet %>%
  mapview::mapshot(file = "m0r10_nolegend.jpg", vwidth = 575, vheight = 375, remove_controls = NULL) #700

```


```{r}
leaflet(options = leafletOptions(zoomControl = FALSE)) %>%
  #addEsriBasemapLayer(esriBasemapLayers$Topographic, autoLabels = TRUE, group = "Topographic map") %>%
  addLegend(pal = pal_fun, values = values(iterated_layer), title = "Percentile", opacity = 1) %>%
  addRasterImage(x = iterated_layer, opacity = 0.8, colors = pal_fun, group = "Predictive layer", project = FALSE) %>%
  addScaleBar(position = "bottomleft") %>%
  setView(lat = 40.870401, lng = -77.329887, zoom = 7) ->
  iterated_leaflet

iterated_leaflet %>%
  mapview::mapshot(file = "legendonly.png", vwidth =700, vheight = 375, remove_controls = NULL)
```


