---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(there)
library(terra)
```

```{r}
prediction_migration <- rast(here_file("Projects", "AMWO-seasonal-weighted-SDM", "code", "penn_shiny_app", "prerender_PA_app", "m10r0.tif")) %>% 
  project("epsg:4326")

prediction_residential <- rast(here_file("Projects", "AMWO-seasonal-weighted-SDM", "code", "penn_shiny_app", "prerender_PA_app", "m0r10.tif")) %>% 
  project(y = prediction_migration) %>%
  resample(prediction_migration)
```

Rescale values to a quantile scale
```{r}
quantiles_mig <- global(prediction_migration, 
                        fun = quantile, 
                        probs = 1:100/100,
                        na.rm = TRUE)

intervals_mig <- findInterval(values(prediction_migration), as.numeric(quantiles_mig[1,]))

prediction_migration <- setValues(prediction_migration, intervals_mig)

quantiles_res <- global(prediction_residential, 
                        fun = quantile, 
                        probs = 1:100/100,
                        na.rm = TRUE)

intervals_res <- findInterval(values(prediction_residential), as.numeric(quantiles_res[1,]))

prediction_residential <- setValues(prediction_residential, intervals_res)
```

```{r}
layers_combined <- c(prediction_residential, prediction_migration)
```

```{r}
correlation_coefficient <- layerCor(x = layers_combined,
         fun = "pearson",
         na.rm = TRUE)

correlation_coefficient
```

