---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(VSURF)
library(raster)
library(there)
library(sf)
```

Explanatory layers
```{r}
#500m
lsm_500m_ai <- raster(here_file("Projects", "Penn_migration_model", "lsm_500m", "lsm_ai_30m_500m_5070.tif"))
lsm_500m_cohesion <- raster(here_file("Projects", "Penn_migration_model", "lsm_500m", "lsm_cohesion_30m_500m_5070.tif"))
lsm_500m_ed <- raster(here_file("Projects", "Penn_migration_model", "lsm_500m", "lsm_ed_30m_500m_5070.tif"))
lsm_500m_pland <- raster(here_file("Projects", "Penn_migration_model", "lsm_500m", "lsm_pland_30m_500m_5070.tif"))
lsm_500m_agri <- raster(here_file("Projects", "Penn_migration_model", "lsm_500m", "lsm_agri_30m_500m_5070.tif"))
lsm_500m_dev <- raster(here_file("Projects", "Penn_migration_model", "lsm_500m", "lsm_dev_30m_500m_5070.tif"))

#1km
lsm_1km_ai <- raster(here_file("Projects", "Penn_migration_model", "lsm_1km", "lsm_ai_90m_1km_5070.tif"))
lsm_1km_cohesion <- raster(here_file("Projects", "Penn_migration_model", "lsm_1km", "lsm_cohesion_90m_1km_5070.tif"))
lsm_1km_ed <- raster(here_file("Projects", "Penn_migration_model", "lsm_1km", "lsm_ed_90m_1km_5070.tif"))
lsm_1km_pland <- raster(here_file("Projects", "Penn_migration_model", "lsm_1km", "lsm_pland_90m_1km_5070.tif"))
lsm_1km_agri <- raster(here_file("Projects", "Penn_migration_model", "lsm_1km", "lsm_agri_90m_1km_5070.tif"))
lsm_1km_dev <- raster(here_file("Projects", "Penn_migration_model", "lsm_1km", "lsm_dev_90m_1km_5070.tif"))

#5km
lsm_5km_ai <- raster(here_file("Projects", "Penn_migration_model", "lsm_5km", "lsm_ai_90m_5km_5070.tif"))
lsm_5km_cohesion <- raster(here_file("Projects", "Penn_migration_model", "lsm_5km", "lsm_cohesion_90m_5km_5070.tif"))
lsm_5km_ed <- raster(here_file("Projects", "Penn_migration_model", "lsm_5km", "lsm_ed_90m_5km_5070.tif"))
lsm_5km_pland <- raster(here_file("Projects", "Penn_migration_model", "lsm_5km", "lsm_pland_90m_5km_5070.tif"))
lsm_5km_agri <- raster(here_file("Projects", "Penn_migration_model", "lsm_5km", "lsm_agri_90m_5km_5070.tif"))
lsm_5km_dev <- raster(here_file("Projects", "Penn_migration_model", "lsm_5km", "lsm_dev_90m_5km_5070.tif"))

#10km
lsm_10km_ai <- raster(here_file("Projects", "Penn_migration_model", "lsm_10km", "lsm_ai_90m_10km_5070.tif"))
lsm_10km_cohesion <- raster(here_file("Projects", "Penn_migration_model", "lsm_10km", "lsm_cohesion_90m_10km_5070.tif"))
lsm_10km_ed <- raster(here_file("Projects", "Penn_migration_model", "lsm_10km", "lsm_ed_90m_10km_5070.tif"))
lsm_10km_pland <- raster(here_file("Projects", "Penn_migration_model", "lsm_10km", "lsm_pland_90m_10km_5070.tif"))
lsm_10km_agri <- raster(here_file("Projects", "Penn_migration_model", "lsm_10km", "lsm_agri_90m_10km_5070.tif"))
lsm_10km_dev <- raster(here_file("Projects", "Penn_migration_model", "lsm_10km", "lsm_dev_90m_10km_5070.tif"))

#landcover: set background values to NA
forest_30m <- here_file("Projects", "Penn_migration_model", "nlcd2016_forestpatches.tif") %>% raster() 
forest_30m[forest_30m == 128] <- NA

#terrain
elev_30m <- here_file("Data", "DEM", "DEM_PA_30m.tif") %>% raster()

slope_30m <- here_file("Projects", "Penn_migration_model", "topographic_wetness_index", "DEM_PA_30slope.tif") %>% raster()

#moisture: replace NAs with the mean value
soil_drainage_30m <- here_file("Data", "SoilDrainage", "soil_drainage_5070.tif") %>% raster()

soil_drainage_30m %>% 
  values() %>%
  mean(na.rm = TRUE) ->
  soil_drainage_30m[is.na(soil_drainage_30m)]

twi_30m <- here_file("Projects", "Penn_migration_model", "topographic_wetness_index", "DEM_PA_30m_twi.tif") %>% raster()

#level 3 ecoregions
ecoregions <- here_file("Data", "physiographic_provinces", "level_iii_ecoregions_pa.tif") %>% raster()

#succession classes
sclass <- here_file("Data", "Landfire_products", "US_200SCLASS", "us_200sclass_pa.tif") %>% raster()
```


Reading in the SGS used and available data, separate into used and available, and transform to match the predictor stack
```{r}
pa_sgs_pres_abs <- read_csv("pa_sgs_pres_abs.csv") %>%
  filter(!is.na(Latitude)) %>%
  mutate(survey_type = 0) %>%
  distinct(Latitude, Longitude, .keep_all = TRUE)
  #group_by(Route) %>%
  #sample_n(1)

state_surveys <- read_csv("pa_statesurveys_pres_abs.csv") %>%
  filter(!is.na(Latitude)) %>%
  mutate(survey_type = 1) %>%
  mutate(Stop = as.character(Stop)) %>%
  distinct(Latitude, Longitude, .keep_all = TRUE)

surveys_all <- bind_rows(pa_sgs_pres_abs, state_surveys)  %>%
  distinct(Latitude, Longitude, .keep_all = TRUE)

used <- surveys_all %>%
  filter(pres_abs == 1) %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>%
  as_Spatial() %>%
  spTransform(crs(lsm_500m_ai))

avail <- surveys_all %>%
  filter(pres_abs == 0) %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>%
  as_Spatial() %>%
  spTransform(crs(lsm_500m_ai))

```


extract values at each point
```{r}
tibble(.rows = length(used)) %>%
  mutate(lsm_500m_ai = raster::extract(lsm_500m_ai, used)) %>%
  mutate(lsm_500m_cohesion = raster::extract(lsm_500m_cohesion, used)) %>%
  mutate(lsm_500m_ed = raster::extract(lsm_500m_ed, used)) %>%
  mutate(lsm_500m_pland = raster::extract(lsm_500m_pland, used)) %>%
  mutate(lsm_500m_agri = raster::extract(lsm_500m_agri, used)) %>%
  mutate(lsm_500m_dev = raster::extract(lsm_500m_dev, used)) %>%
  mutate(lsm_1km_ai = raster::extract(lsm_1km_ai, used)) %>%
  mutate(lsm_1km_cohesion = raster::extract(lsm_1km_cohesion, used)) %>%
  mutate(lsm_1km_ed = raster::extract(lsm_1km_ed, used)) %>%
  mutate(lsm_1km_pland = raster::extract(lsm_1km_pland, used)) %>%
  mutate(lsm_1km_agri = raster::extract(lsm_1km_agri, used)) %>%
  mutate(lsm_1km_dev = raster::extract(lsm_1km_dev, used)) %>%
  mutate(lsm_5km_ai = raster::extract(lsm_5km_ai, used)) %>%
  mutate(lsm_5km_cohesion = raster::extract(lsm_5km_cohesion, used)) %>%
  mutate(lsm_5km_ed = raster::extract(lsm_5km_ed, used)) %>%
  mutate(lsm_5km_pland = raster::extract(lsm_5km_pland, used)) %>%
  mutate(lsm_5km_agri = raster::extract(lsm_5km_agri, used)) %>%
  mutate(lsm_5km_dev = raster::extract(lsm_5km_dev, used)) %>%
  mutate(lsm_10km_ai = raster::extract(lsm_10km_ai, used)) %>%
  mutate(lsm_10km_cohesion = raster::extract(lsm_10km_cohesion, used)) %>%
  mutate(lsm_10km_ed = raster::extract(lsm_10km_ed, used)) %>%
  mutate(lsm_10km_pland = raster::extract(lsm_10km_pland, used)) %>%
  mutate(lsm_10km_agri = raster::extract(lsm_10km_agri, used)) %>%
  mutate(lsm_10km_dev = raster::extract(lsm_10km_dev, used)) %>%
  mutate(forest_30m = raster::extract(forest_30m, used)) %>%
  mutate(elev_30m = raster::extract(elev_30m, used)) %>%
  mutate(slope_30m = raster::extract(slope_30m, used)) %>%
  mutate(soil_drainage_30m = raster::extract(soil_drainage_30m, used)) %>%
  mutate(twi_30m = raster::extract(twi_30m, used)) %>%
  mutate(ecoregions = raster::extract(ecoregions, used)) %>%
  mutate(sclass = raster::extract(sclass, used)) -> 
  used_values

used_values$survey_type <- used@data$survey_type

tibble(.rows = length(avail)) %>%
  mutate(lsm_500m_ai = raster::extract(lsm_500m_ai, avail)) %>%
  mutate(lsm_500m_cohesion = raster::extract(lsm_500m_cohesion, avail)) %>%
  mutate(lsm_500m_ed = raster::extract(lsm_500m_ed, avail)) %>%
  mutate(lsm_500m_pland = raster::extract(lsm_500m_pland, avail)) %>%
  mutate(lsm_500m_agri = raster::extract(lsm_500m_agri, avail)) %>%
  mutate(lsm_500m_dev = raster::extract(lsm_500m_dev, avail)) %>%
  mutate(lsm_1km_ai = raster::extract(lsm_1km_ai, avail)) %>%
  mutate(lsm_1km_cohesion = raster::extract(lsm_1km_cohesion, avail)) %>%
  mutate(lsm_1km_ed = raster::extract(lsm_1km_ed, avail)) %>%
  mutate(lsm_1km_pland = raster::extract(lsm_1km_pland, avail)) %>%
  mutate(lsm_1km_agri = raster::extract(lsm_1km_agri, avail)) %>%
  mutate(lsm_1km_dev = raster::extract(lsm_1km_dev, avail)) %>%
  mutate(lsm_5km_ai = raster::extract(lsm_5km_ai, avail)) %>%
  mutate(lsm_5km_cohesion = raster::extract(lsm_5km_cohesion, avail)) %>%
  mutate(lsm_5km_ed = raster::extract(lsm_5km_ed, avail)) %>%
  mutate(lsm_5km_pland = raster::extract(lsm_5km_pland, avail)) %>%
  mutate(lsm_5km_agri = raster::extract(lsm_5km_agri, avail)) %>%
  mutate(lsm_5km_dev = raster::extract(lsm_5km_dev, avail)) %>%
  mutate(lsm_10km_ai = raster::extract(lsm_10km_ai, avail)) %>%
  mutate(lsm_10km_cohesion = raster::extract(lsm_10km_cohesion, avail)) %>%
  mutate(lsm_10km_ed = raster::extract(lsm_10km_ed, avail)) %>%
  mutate(lsm_10km_pland = raster::extract(lsm_10km_pland, avail)) %>%
  mutate(lsm_10km_agri = raster::extract(lsm_10km_agri, avail)) %>%
  mutate(lsm_10km_dev = raster::extract(lsm_10km_dev, avail)) %>%
  mutate(forest_30m = raster::extract(forest_30m, avail)) %>%
  mutate(elev_30m = raster::extract(elev_30m, avail)) %>%
  mutate(slope_30m = raster::extract(slope_30m, avail)) %>%
  mutate(soil_drainage_30m = raster::extract(soil_drainage_30m, avail)) %>%
  mutate(twi_30m = raster::extract(twi_30m, avail)) %>%
  mutate(ecoregions = raster::extract(ecoregions, avail)) %>%
  mutate(sclass = raster::extract(sclass, avail)) ->  
  avail_values

avail_values$survey_type <- avail@data$survey_type

```

Remove any observations with at least one NA or infinite value
```{r}
used_values %>%
  drop_na() %>%
  filter(if_all(.fns = ~ !is.infinite(.))) -> 
  used_values

avail_values %>%
  drop_na() %>%
  filter(if_all(.fns = ~ !is.infinite(.))) -> 
  avail_values
```

Creating VSURF object
```{r}
mig_vsurf <- list()
mig_vsurf$x <- bind_rows(used_values, avail_values)
mig_vsurf$y <- append(rep(1, times = nrow(used_values)), rep(0, times = nrow(avail_values))) %>% as_factor()
```

Running VSURF
```{r}
mig_vsurf_results <- VSURF(x = mig_vsurf$x, y = mig_vsurf$y, parallel = TRUE, ncores = 8)
```

Inspecting results
```{r}
#threshold variables
names(mig_vsurf$x)[mig_vsurf_results$varselect.thres]

names(mig_vsurf$x)[mig_vsurf_results$varselect.thres] %>% length()

#interpretation variables
names(mig_vsurf$x)[mig_vsurf_results$varselect.interp]

names(mig_vsurf$x)[mig_vsurf_results$varselect.interp] %>% length()


#prediction variables
names(mig_vsurf$x)[mig_vsurf_results$varselect.pred]

names(mig_vsurf$x)[mig_vsurf_results$varselect.pred] %>% length()
```

