---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(randomForest)
library(SDMtune)
library(here)
```

```{r}
model_mig <- readRDS(here("methods", "Penn_migration_model", "model_migratory.rds"))

model_res <- readRDS(here("methods", "Penn_residential_model", "model_residential.rds"))
```

Calculating permutation importance: "returns the average and the standard deviation of the permutation importances of the single models"

normalized to % decrease in training AUC (higher is more important)

Default is 10 permutations
```{r}
vi_mig <- varImp(model_mig)
vi_res <- varImp(model_res)
```

Combine into a single dataframe
```{r}
vi_mig$model <- "Migratory"
vi_res$model <- "Breeding"

vi <- bind_rows(vi_mig,vi_res) %>% 
  mutate(variable_clean = recode_values(Variable,
                                        "soil_drainage_30m" ~ "Soil drainage",
                                        "lsm_10km_dev" ~ " % Developed (10km)",
                                        "twi_30m" ~ "Topographic wetness index",
                                        "lsm_10km_ed" ~ "Edge density (10km)",
                                        "lsm_1km_dev" ~ "% Developed (1km)",
                                        "lsm_10km_agri" ~ "% Agricultural (10km)",
                                        "slope_30m" ~ "Slope",
                                        "elev_30m" ~ "Elevation",
                                        "forest_30m" ~ "Forest"
  ),
  Permutation_importance = Permutation_importance/100,
  sd = sd/100)
```

Let's figure out how to plot it
```{r fig.height=4, fig.width=6}
ggplot(vi, aes(x = tidytext::reorder_within(variable_clean, Permutation_importance, model), y = Permutation_importance)) +
  # geom_point(color = "black", fill = "white") +
  # geom_errorbar(aes(ymin = Permutation_importance - 1.96*sd, ymax = Permutation_importance + 1.96*sd)) +
  geom_pointrange(
    aes(ymin = Permutation_importance - 1.96*sd, ymax = Permutation_importance + 1.96*sd),
    linewidth  = 0.5,
    size       = 0.4,
    shape      = 21,          # filled circle with border
    fill       = "white",
    color      = "black"
  ) +
  geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
  facet_wrap(vars(model), scales = "free_y") +
  theme_bw() +
  labs(y = "Permutation importance") +
  theme(axis.text.x = element_text(angle = 315, hjust = 0, size = 9)) +
  #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  scale_y_continuous(labels = scales::percent) +
  tidytext::scale_x_reordered() +
  theme(axis.title.y = element_blank()) +
  coord_flip()

ggsave(here("figures_results", "variable_importance", "var_imp.png"), dpi = 600, units = "in", height = 4, width = 6)
```

