---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(SDMtune)
library(here)
library(raster)
library(sp)
library(sf)
library(ecospat)
```

Read in predictor stack
```{r}
predictor_stack_full <- stackOpen(here("methods", "Penn_migration_model", "predictor_stack_full_mig.stk"))

names(predictor_stack_full) <- c("lsm_500m_ai", "lsm_500m_cohesion", "lsm_500m_ed", "lsm_500m_pland", "lsm_500m_agri", "lsm_500m_dev", "lsm_1km_ai", "lsm_1km_cohesion", "lsm_1km_ed", "lsm_1km_pland", "lsm_1km_agri", "lsm_1km_dev", "lsm_5km_ai", "lsm_5km_cohesion", "lsm_5km_ed", "lsm_5km_pland", "lsm_5km_agri", "lsm_5km_dev", "lsm_10km_ai", "lsm_10km_cohesion", "lsm_10km_ed", "lsm_10km_pland", "lsm_10km_agri", "lsm_10km_dev", "forest_30m", "elev_30m", "slope_30m", "soil_drainage_30m", "twi_30m", "ecoregions", "sclass")

predictor_stack_full <- subset(predictor_stack_full, c("lsm_500m_ai", "lsm_500m_cohesion", "lsm_500m_ed", "lsm_500m_pland", "lsm_500m_agri", "lsm_500m_dev", "lsm_1km_ai", "lsm_1km_cohesion", "lsm_1km_ed", "lsm_1km_pland", "lsm_1km_agri", "lsm_1km_dev", "lsm_5km_ai", "lsm_5km_cohesion", "lsm_5km_ed", "lsm_5km_pland", "lsm_5km_agri", "lsm_5km_dev", "lsm_10km_ai", "lsm_10km_cohesion", "lsm_10km_ed", "lsm_10km_pland", "lsm_10km_agri", "lsm_10km_dev", "forest_30m", "elev_30m", "slope_30m", "soil_drainage_30m", "twi_30m")) #remove "ecoregions", "sclass"

```

Read in the used points, and transform the used and available points to match the predictor stack
```{r}
used <- st_read(dsn = here("methods", "Penn_migration_model", "movebank_locations", "dispersing_points_pa_6_2_2021.shp")) %>% 
  st_transform(st_crs(predictor_stack_full)) %>% 
  as_Spatial() 

avail_unbiased <- readRDS(here("methods", "Penn_migration_model", "avail_unbiased.rds"))

set.seed(8)

avail_unbiased <- avail_unbiased %>%
  st_as_sf() %>% 
  st_transform(st_crs(predictor_stack_full)) %>% 
  slice_sample(n = 2000) %>% 
  as_Spatial()
```

Prep SDMs
```{r}
swd <- prepareSWD(species = "Scolopax minor", 
           env = terra::rast(predictor_stack_full), 
           p = rename(as.data.frame(used@coords), x = coords.x1, y = coords.x2), 
           a = as.data.frame(avail_unbiased@coords),
           categorical = c("forest_30m"))

kfolds <- randomFolds(swd, k = 5, only_presence = TRUE, seed = 8)

train_data_1 <- swd
train_data_1@coords <- train_data_1@coords[kfolds$train[,1],]
train_data_1@data <- train_data_1@data[kfolds$train[,1],]
train_data_1@pa <- train_data_1@pa[kfolds$train[,1]]

train_data_2 <- swd
train_data_2@coords <- train_data_2@coords[kfolds$train[,2],]
train_data_2@data <- train_data_2@data[kfolds$train[,2],]
train_data_2@pa <- train_data_2@pa[kfolds$train[,2]]

train_data_3 <- swd
train_data_3@coords <- train_data_3@coords[kfolds$train[,3],]
train_data_3@data <- train_data_3@data[kfolds$train[,3],]
train_data_3@pa <- train_data_3@pa[kfolds$train[,3]]

train_data_4 <- swd
train_data_4@coords <- train_data_4@coords[kfolds$train[,4],]
train_data_4@data <- train_data_4@data[kfolds$train[,4],]
train_data_4@pa <- train_data_4@pa[kfolds$train[,4]]

train_data_5 <- swd
train_data_5@coords <- train_data_5@coords[kfolds$train[,5],]
train_data_5@data <- train_data_5@data[kfolds$train[,5],]
train_data_5@pa <- train_data_5@pa[kfolds$train[,5]]
```

RF test
```{r}
model_rf_1 <- train(method = "RF",
               data = train_data_1, 
               mtry = 5, #floor(sqrt(number of variables))
               ntree = 500,
               nodesize = 1)

model_rf_2 <- train(method = "RF",
               data = train_data_2,
               mtry = 5,
               ntree = 500,
               nodesize = 1)

model_rf_3 <- train(method = "RF",
               data = train_data_3,
              mtry = 5,
               ntree = 500,
               nodesize = 1)

model_rf_4 <- train(method = "RF",
               data = train_data_4,
               mtry = 5,
               ntree = 500,
               nodesize = 1)

model_rf_5 <- train(method = "RF",
               data = train_data_5,
               mtry = 5,
               ntree = 500,
               nodesize = 1)

boyce_rf <- map2_dbl(1:5,list(model_rf_1, model_rf_2, model_rf_3, model_rf_4, model_rf_5), function(x, k){
  rf_predictions <- tibble(pres_abs = swd@pa[kfolds$test[,x]],
                             value = predict(k, swd)[kfolds$test[,x]])
  
  predicted_background <- rf_predictions %>% 
    filter(pres_abs==0) %>% 
    pull(value)
  
  predicted_used <- rf_predictions %>% 
    filter(pres_abs==1) %>% 
    pull(value)
  
  boyce_results <- ecospat.boyce(predicted_background, predicted_used)
  
  boyce_results$cor %>% 
    return()
})

mean(boyce_rf)

# rf_full <- train(method = "RF", data = swd_full, swd_full_folds, ntree = 500)
# 
# auc(rf_full, test = TRUE) #0.8463698
# #The TSS scores are measured from 1 to + 1, with 1 signifying perfect agreement and 0.60 to 0.90 suggesting good to excellent model performance (Allouche et al.
# tss(rf_full, test = TRUE) #0.5858761
```

Maxent
```{r}
model_max_1 <- train(method = "Maxnet",
               data = train_data_1)

model_max_2 <- train(method = "Maxnet",
               data = train_data_2)

model_max_3 <- train(method = "Maxnet",
               data = train_data_3)

model_max_4 <- train(method = "Maxnet",
               data = train_data_4)

model_max_5 <- train(method = "Maxnet",
               data = train_data_5)

boyce_max <- map2_dbl(1:5,list(model_max_1, model_max_2, model_max_3, model_max_4, model_max_5), function(x, k){
  rf_predictions <- tibble(pres_abs = swd@pa[kfolds$test[,x]],
                             value = predict(k, swd)[kfolds$test[,x]])
  
  predicted_background <- rf_predictions %>% 
    filter(pres_abs==0) %>% 
    pull(value)
  
  predicted_used <- rf_predictions %>% 
    filter(pres_abs==1) %>% 
    pull(value)
  
  boyce_results <- ecospat.boyce(predicted_background, predicted_used)
  
  boyce_results$cor %>% 
    return()
})

mean(boyce_max)

# maxnet_full <- train(method = "Maxnet", data = swd_full, swd_full_folds)
# 
# auc(maxnet_full, test = TRUE) #0.616897100
# #The TSS scores are measured from 1 to + 1, with 1 signifying perfect agreement and 0.60 to 0.90 suggesting good to excellent model performance (Allouche et al.
# tss(maxnet_full, test = TRUE) #0.2614707
```

Boosted Regression Tree test
```{r}
model_brt_1 <- train(method = "BRT",
               data = train_data_1)

model_brt_2 <- train(method = "BRT",
               data = train_data_2)

model_brt_3 <- train(method = "BRT",
               data = train_data_3)

model_brt_4 <- train(method = "BRT",
               data = train_data_4)

model_brt_5 <- train(method = "BRT",
               data = train_data_5)

boyce_brt <- map2_dbl(1:5,list(model_brt_1, model_brt_2, model_brt_3, model_brt_4, model_brt_5), function(x, k){
  rf_predictions <- tibble(pres_abs = swd@pa[kfolds$test[,x]],
                             value = predict(k, swd)[kfolds$test[,x]])
  
  predicted_background <- rf_predictions %>% 
    filter(pres_abs==0) %>% 
    pull(value)
  
  predicted_used <- rf_predictions %>% 
    filter(pres_abs==1) %>% 
    pull(value)
  
  boyce_results <- ecospat.boyce(predicted_background, predicted_used)
  
  boyce_results$cor %>% 
    return()
})

mean(boyce_brt)

# brt_unbiased <- train(method = "BRT", data = swd_full, swd_full_folds)
# 
# auc(brt_unbiased, test = TRUE) #0.6284959
# #The TSS scores are measured from 1 to + 1, with 1 signifying perfect agreement and 0.60 to 0.90 suggesting good to excellent model performance (Allouche et al.
# tss(brt_unbiased, test = TRUE) #0.2857015
```
