---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(raster)
library(sf)
library(there)
```

Predictive layers
```{r}
#500m
lsm_500m_ai <- raster(here_file("Projects", "Penn_migration_model", "lsm_500m", "lsm_ai_30m_500m_5070.tif"))
lsm_500m_cohesion <- raster(here_file("Projects", "Penn_migration_model", "lsm_500m", "lsm_cohesion_30m_500m_5070.tif"))
lsm_500m_ed <- raster(here_file("Projects", "Penn_migration_model", "lsm_500m", "lsm_ed_30m_500m_5070.tif"))
lsm_500m_pland <- raster(here_file("Projects", "Penn_migration_model", "lsm_500m", "lsm_pland_30m_500m_5070.tif"))
lsm_500m_agri <- raster(here_file("Projects", "Penn_migration_model", "lsm_500m", "lsm_agri_30m_500m_5070.tif"))
lsm_500m_dev <- raster(here_file("Projects", "Penn_migration_model", "lsm_500m", "lsm_dev_30m_500m_5070.tif"))

#1km
lsm_1km_ai <- raster(here_file("Projects", "Penn_migration_model", "lsm_1km", "lsm_ai_90m_1km_5070.tif"))
lsm_1km_cohesion <- raster(here_file("Projects", "Penn_migration_model", "lsm_1km", "lsm_cohesion_90m_1km_5070.tif"))
lsm_1km_ed <- raster(here_file("Projects", "Penn_migration_model", "lsm_1km", "lsm_ed_90m_1km_5070.tif"))
lsm_1km_pland <- raster(here_file("Projects", "Penn_migration_model", "lsm_1km", "lsm_pland_90m_1km_5070.tif"))
lsm_1km_agri <- raster(here_file("Projects", "Penn_migration_model", "lsm_1km", "lsm_agri_90m_1km_5070.tif"))
lsm_1km_dev <- raster(here_file("Projects", "Penn_migration_model", "lsm_1km", "lsm_dev_90m_1km_5070.tif"))

#5km
lsm_5km_ai <- raster(here_file("Projects", "Penn_migration_model", "lsm_5km", "lsm_ai_90m_5km_5070.tif"))
lsm_5km_cohesion <- raster(here_file("Projects", "Penn_migration_model", "lsm_5km", "lsm_cohesion_90m_5km_5070.tif"))
lsm_5km_ed <- raster(here_file("Projects", "Penn_migration_model", "lsm_5km", "lsm_ed_90m_5km_5070.tif"))
lsm_5km_pland <- raster(here_file("Projects", "Penn_migration_model", "lsm_5km", "lsm_pland_90m_5km_5070.tif"))
lsm_5km_agri <- raster(here_file("Projects", "Penn_migration_model", "lsm_5km", "lsm_agri_90m_5km_5070.tif"))
lsm_5km_dev <- raster(here_file("Projects", "Penn_migration_model", "lsm_5km", "lsm_dev_90m_5km_5070.tif"))

#10km
lsm_10km_ai <- raster(here_file("Projects", "Penn_migration_model", "lsm_10km", "lsm_ai_90m_10km_5070.tif"))
lsm_10km_cohesion <- raster(here_file("Projects", "Penn_migration_model", "lsm_10km", "lsm_cohesion_90m_10km_5070.tif"))
lsm_10km_ed <- raster(here_file("Projects", "Penn_migration_model", "lsm_10km", "lsm_ed_90m_10km_5070.tif"))
lsm_10km_pland <- raster(here_file("Projects", "Penn_migration_model", "lsm_10km", "lsm_pland_90m_10km_5070.tif"))
lsm_10km_agri <- raster(here_file("Projects", "Penn_migration_model", "lsm_10km", "lsm_agri_90m_10km_5070.tif"))
lsm_10km_dev <- raster(here_file("Projects", "Penn_migration_model", "lsm_10km", "lsm_dev_90m_10km_5070.tif"))

#landcover: set background values to NA
forest_30m <- here_file("Projects", "Penn_migration_model", "nlcd2016_forestpatches.tif") %>% raster() 
forest_30m[forest_30m == 128] <- NA

#terrain
elev_30m <- here_file("Data", "DEM", "DEM_PA_30m.tif") %>% raster()

slope_30m <- here_file("Projects", "Penn_migration_model", "topographic_wetness_index", "DEM_PA_30slope.tif") %>% raster()

#moisture: replace NAs with the mean value
soil_drainage_30m <- here_file("Data", "SoilDrainage", "soil_drainage_5070.tif") %>% raster()

soil_drainage_30m %>% 
  values() %>%
  mean(na.rm = TRUE) ->
  soil_drainage_30m[is.na(soil_drainage_30m)]

twi_30m <- here_file("Projects", "Penn_migration_model", "topographic_wetness_index", "DEM_PA_30m_twi.tif") %>% raster()

#level 3 ecoregions
ecoregions <- here_file("Data", "physiographic_provinces", "level_iii_ecoregions_pa.tif") %>% raster()

#succession classes
sclass <- here_file("Data", "Landfire_products", "US_200SCLASS", "us_200sclass_pa.tif") %>% raster()
```

This is mostly relic code which is used here to draw available points
```{r}
pa_mig_corridor <- here_file("Projects", "Migratory_corridor_modeling", "mig_corridor_spring_pa_1_3_21.tif") %>% raster()

#divide the raster by the sum so that all cells total to 1
pa_mig_corridor <- pa_mig_corridor/cellStats(pa_mig_corridor, stat = "sum")

pa_mig_corridor_4326 <- projectRaster(pa_mig_corridor, crs = CRS("+init=epsg:4326"))
```

Draw available points (unbiased)
```{r}
random_points <- enmSdm::sampleRast(x = pa_mig_corridor_4326, n = 10000, replace = TRUE, prob = FALSE) %>%
  as.data.frame() %>%
  st_as_sf(coords = c("x", "y"), crs = 4326) %>%
  st_transform(st_crs(twi_30m))
```

Reading in the model layer
```{r}
model_layer <- here_file("Projects", "Penn_residential_model", "rf_random_effects_6_14_21_linktransformed.tif") %>% raster()
```

Extract the values for the predictor variables and the model layer at the random points
```{r}
random_points %>%
  mutate(v_lsm_5km_cohesion = raster::extract(x = lsm_5km_cohesion, y = as_Spatial(random_points), method = "simple")) %>%
  mutate(v_lsm_5km_pland = raster::extract(x = lsm_5km_pland, y = as_Spatial(random_points), method = "simple")) %>%
  mutate(v_lsm_5km_agri = raster::extract(x = lsm_5km_agri, y = as_Spatial(random_points), method = "simple")) %>%
  mutate(v_lsm_5km_dev = raster::extract(x = lsm_5km_dev, y = as_Spatial(random_points), method = "simple")) %>%
  mutate(v_ecoregions = raster::extract(x = ecoregions, y = as_Spatial(random_points), method = "simple")) %>%
  mutate(v_model = raster::extract(x = model_layer, y = as_Spatial(random_points), method = "simple")) ->
  random_extracted
```


Run and save the predictor relationship graphs
```{r}
random_extracted %>%
  filter(v_lsm_5km_cohesion < 1e38) %>%
  ggplot(mapping = aes(x = v_lsm_5km_cohesion, y = v_model)) +
  geom_point() +
  ylab("Probability of residential use") +
  xlab("Cohesion (5k)") +
  theme_bw()
ggsave(here_file("Projects", "Penn_residential_model", "predictor_relationship_graphs", "cohesion_5k.jpg"))

ggplot(random_extracted, mapping = aes(x = v_lsm_5km_pland, y = v_model)) +
  geom_point() +
  ylab("Probability of residential use") +
  xlab("% Forest (5k)") +
  theme_bw()
ggsave(here_file("Projects", "Penn_residential_model", "predictor_relationship_graphs", "pland_5k.jpg"))

ggplot(random_extracted, mapping = aes(x = v_lsm_5km_agri, y = v_model)) +
  geom_point() +
  ylab("Probability of residential use") +
  xlab("% Agriculture (5k)") +
  theme_bw()
ggsave(here_file("Projects", "Penn_residential_model", "predictor_relationship_graphs", "agri_5k.jpg"))

ggplot(random_extracted, mapping = aes(x = v_lsm_5km_dev, y = v_model)) +
  geom_point() +
  ylab("Probability of residential use") +
  xlab("% Developed (5k)") +
  theme_bw()
ggsave(here_file("Projects", "Penn_residential_model", "predictor_relationship_graphs", "dev_5k.jpg"))

random_extracted %>%
  mutate(v_ecoregions = recode(v_ecoregions, "1" = "Northeastern Highlands", '2' = "Northern Allegheny Plateau", '3' = "Erie Drift Plain", '4' = "North Central Appalachians", '5' = "Middle Atlantic Coastal Plain", '6' = "Northern Piedmont", '7' = "Blue Ridge", '8' = "Ridge and Valley", '9' = "Central Appalachians", '10' = "Western Allegheny Plateau", '11' = "Eastern Great Lakes Lowlands")) %>%
  filter(!is.na(v_ecoregions)) %>%
  ggplot(mapping = aes(x = v_ecoregions, y = v_model, group = v_ecoregions)) +
  geom_boxplot() +
  ylab("Probability of residential use") +
  xlab("Level 3 Ecoregions") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45)) + 
  theme(axis.text.x = element_text(hjust = 1))
ggsave(here_file("Projects", "Penn_residential_model", "predictor_relationship_graphs", "ecoregions.jpg"))

```

