---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(terra)
library(sf)
library(tidyterra)
library(there)
library(ggpubr)
library(ggspatial)
```

```{r}
prediction_migration <- rast(here_file("Projects", "AMWO-seasonal-weighted-SDM", "code", "penn_shiny_app", "prerender_PA_app", "m10r0.tif")) %>% 
  project("epsg:4326")

prediction_residential <- rast(here_file("Projects", "AMWO-seasonal-weighted-SDM", "code", "penn_shiny_app", "prerender_PA_app", "m0r10.tif")) %>% 
  project(y = prediction_migration) %>%
  resample(prediction_migration)

basemap <- rast(here_file("Data", "basemaps", "esri_lightgrey", "esri_lightgrey_36_48_4326_pa.tif"))
```

Rescale values to a quantile scale
```{r}
quantiles_mig <- global(prediction_migration, 
                        fun = quantile, 
                        probs = 1:100/100,
                        na.rm = TRUE)

intervals_mig <- findInterval(values(prediction_migration), as.numeric(quantiles_mig[1,]))

prediction_migration <- setValues(prediction_migration, intervals_mig)

quantiles_res <- global(prediction_residential, 
                        fun = quantile, 
                        probs = 1:100/100,
                        na.rm = TRUE)

intervals_res <- findInterval(values(prediction_residential), as.numeric(quantiles_res[1,]))

prediction_residential <- setValues(prediction_residential, intervals_res)
```


```{r}
pal <- leaflet::colorNumeric(palette = "RdYlBu", domain = c(0, 100), reverse = TRUE, na.color = NA)

migplot <- ggplot() + 
  theme_void() +
  geom_spatraster_rgb(data = basemap) +
  geom_spatraster(data = prediction_migration) +
  scale_fill_gradientn(colours = pal(1:100), na.value = NA) +
  lims(x = c(81, 74.5), y = c(39.4, 42.4)) +
  labs(fill = "Percentile ") +
  theme(legend.title = element_text(margin = margin(b = 3)))

migplot2 <- migplot +
  annotation_north_arrow(location = "br",
                         which_north = "true",
                         height = unit(1.5/2, "cm"),
                         width = unit(1.5/2, "cm"),
                         pad_x = unit(0.75, "cm"),
                         pad_y = unit(0.5, "cm"),
                         style = ggspatial::north_arrow_orienteering(
                           fill = c("grey40", "white"),
                           line_col = "grey20",
                           text_size = 8
                         )) +
  annotation_scale(location = "bl", width_hint = 0.3, bar_cols = c("grey40", "white"),
                   pad_x = unit(0.9, "cm"),
                   pad_y = unit(0.5, "cm"),)

resplot <- ggplot() +
  theme_void() +
  geom_spatraster_rgb(data = basemap) + #maxcell = 1e+07
  geom_spatraster(data = prediction_residential) +
  scale_fill_gradientn(colours = pal(1:100), na.value = NA) +
  lims(x = c(81, 74.5), y = c(39.4, 42.4)) +
  labs(fill = "Percentile ") +
  theme(legend.title = element_text(margin = margin(b = 3)))

resplot2 <- resplot +
  annotation_north_arrow(location = "br",
                         which_north = "true",
                         height = unit(1.5/2, "cm"),
                         width = unit(1.5/2, "cm"),
                         pad_x = unit(0.75, "cm"),
                         pad_y = unit(0.5, "cm"),
                         style = ggspatial::north_arrow_orienteering(
                           fill = c("grey40", "white"),
                           line_col = "grey20",
                           text_size = 8
                         )) +
  annotation_scale(location = "bl", width_hint = 0.3, bar_cols = c("grey40", "white"),
                   pad_x = unit(0.9, "cm"),
                   pad_y = unit(0.5, "cm"),)
```

Mesh into a single feature
```{r}
comp_map <- ggarrange(plotlist =  list(resplot2, migplot2),
                      ncol = 1,
                      nrow = 2,
                      labels = c("Breeding", "Migratory"),
                      common.legend = TRUE,
                      legend = "right",
                      hjust = -0.3)

ggsave(filename = "comparative_maps_4_26_23.png", plot = comp_map, dpi = 300, bg = "white",
       width = 6,
       height = 7)
```

