---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(sf)
library(terra)
library(mapview)
library(there)
```

Read in files
```{r}
pa_ecoregions <- st_read(here_file("Data", "physiographic_provinces", "level_iii_ecoregions_pa.shp"))

pa_nlcd <- here_file("Data", "NLCD_products", "landcover_2016", "NLCD_2016_PA.tif") %>% 
  rast()
```

Create ecoregion-specific shapefiles
```{r}
northern_piedmont <- pa_ecoregions %>% 
  filter(US_L3NAME == "Northern Piedmont")

nc_appl <- pa_ecoregions %>% 
  filter(US_L3NAME == "North Central Appalachians")
```

Mask NLCD to each ecoregion and then count frequency
```{r}
#northern piedmont
nlcd_northern_piedmont <- mask(x = pa_nlcd, mask = northern_piedmont)

#adjusting the labels for this categorical layer so that freq counts it correctly
cats(nlcd_northern_piedmont)
activeCat(nlcd_northern_piedmont) <- 4
levels(nlcd_northern_piedmont)

freqtable_northern_piedmont <- freq(nlcd_northern_piedmont)

freqtable_northern_piedmont$percent <- (freqtable_northern_piedmont$count*100)/sum(freqtable_northern_piedmont$count)


# North central appalachians
nlcd_nc_appl <- mask(x = pa_nlcd, mask = nc_appl)

#adjusting the labels for this categorical layer so that freq counts it correctly
cats(nlcd_nc_appl)
activeCat(nlcd_nc_appl) <- 4
levels(nlcd_nc_appl)

freqtable_nlcd_nc_appl <- freq(nlcd_nc_appl)

freqtable_nlcd_nc_appl$percent <- (freqtable_nlcd_nc_appl$count*100)/sum(freqtable_nlcd_nc_appl$count)
```

